### ISSUE TITLE
Add example link to the Leiningen template for project

### ISSUE THREAD

**Issue by agilecreativity** [Mayvenn/limo#2]
Hi @jeffh 

I have created the simple [Leiningen template](https://github.com/agilecreativity/limo-driver) to create the project that use Limo quickly.

Could you add this link to the README.md or some where that you feel appropriate.

Cheers,
Burin

**Comment by jeffh** [comment]
Hey Burin,

That’s awesome! We’re using it primarily for tests, which seems different from the leiningen template that you have which seems to be writing programs that automate something?

Either way, if you send a pull request I can review it.

**Comment by agilecreativity** [comment]
Hi @jeffh 
I created the new PR with basic information to README.md
Please feel free to edit/review as you see fit.

Thanks again.
Burin
