### ISSUE TITLE
click doesn't pass driver through to wait-until-clickable

### ISSUE THREAD

**Issue by wiseman** [Mayvenn/limo#7]
When `click` [calls `wait-until-clickable`](https://github.com/Mayvenn/limo/blob/0b92cea28e0a55426bc84a71d9e31a56aebc9f58/src/limo/api.clj#L390) it doesn't pass the driver argument, so if you don't have a default `*driver*` it fails with a `NullPointerException`.

```
(defn click
  ([selector-or-element] (click *driver* selector-or-element))
  ([driver selector-or-element]
   (scroll-to driver selector-or-element)
   (wait-until-clickable selector-or-element)
   (wait-for ["click" selector-or-element]
             (.click (element driver selector-or-element))
             true)))
```

**Comment by wiseman** [comment]
This might be the same issue as #6 .

**Comment by wiseman** [comment]
`scroll-to` has a [similar bug](https://github.com/Mayvenn/limo/blob/0b92cea28e0a55426bc84a71d9e31a56aebc9f58/src/limo/api.clj#L372).

**Comment by sheelc** [comment]
@wiseman nice catch! We're guilty of leaning on the default `*driver*` for most cases (which is probably why we haven't run into this in our day to day). I think fixing this would solve #6 

Also, there are several uses of `wait-until` that don't pass the driver through. Probably worth an audit of all calls of `wait-until`/`wait-until-clickable` and thread the driver through @jeffh?

**Comment by wiseman** [comment]
Yeah, for my current use case I have two drivers open, which I'm sure is unusual.

**Comment by jeffh** [comment]
Yeah, we need to audit that all of the functions properly thread driver through

**Comment by jeffh** [comment]
@wiseman, I've done a first-pass through the APIs to properly thread driver through on `master`. Let me know how it works.

I need to do another walk through for APIs that were added since I made those changes. I figured it would be better to push this instead of waiting until all of them got properly updated.

**Comment by jeffh** [comment]
This should be fixed in the latest release.
